### ISSUE TITLE
Ticket System BLUFOR /Insurgents

### ISSUE THREAD

**Issue by Achluophobia** [smonti/dusty-lair#16]

**Comment by r4vn** [comment]
A beta version of the ticket system is available since f389c7e3a3dbea7a0073a7f963476c634f1fecb2. Still needs some testing and maybe polishing.

**Comment by r4vn** [comment]
Completed with the addition of civilians (#20) in 4dc5c3921a4b68797568c52a8388518bd8c8a32a
