### ISSUE TITLE
UAV 

### ISSUE THREAD

**Issue by Achluophobia** [smonti/dusty-lair#22]
There should be an UAV.

Option A: Small UAV in a backpack of an UAV Operator. 

Option B: Big UAV in the Air, in standby.(without missiles)

**Comment by Achluophobia** [comment]
Tested "big UAV version" doesn`t worked well

Option A is better .

**Comment by r4vn** [comment]
Same as air surveillance by MELB.

**Comment by Achluophobia** [comment]
Naaah.
